crypto_pipeline:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: airflow
      password: airflow
      port: 5432
      dbname: crypto_warehouse
      schema: analytics
      threads: 4