version: "3.8"

x-airflow-common: &airflow-common
  image: airflow-custom
  build:
    context: .
    dockerfile: Dockerfile
  env_file:
    - .env
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    AIRFLOW__DATABASE__SQL_ALCHEMY_POOL_PRE_PING: "True"
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/plugins:/opt/airflow/plugins
    - ./ingestion:/opt/airflow/ingestion
    - ./scripts:/opt/airflow/scripts
    - ./quality:/opt/airflow/quality
    - ./dbt:/opt/airflow/dbt
  depends_on:
    postgres:
      condition: service_healthy

services:

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      -c "
      echo 'Esperando PostgreSQL iniciar...';
      until pg_isready -h ${POSTGRES_HOST} -p 5432 -U ${POSTGRES_USER}; do
        sleep 2;
      done;

      echo 'PostgreSQL pronto';

      airflow db migrate &&
      airflow users create --username ${AIRFLOW_ADMIN_USER} --password ${AIRFLOW_ADMIN_PASSWORD} --firstname admin --lastname admin --role Admin --email admin@email.com
      "

  postgres:
    image: postgres:17
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./warehouse/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    restart: always
    env_file:
      - .env
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 15s
      timeout: 10s
      retries: 5

  createbuckets:
    image: minio/mc
    restart: on-failure
    depends_on:
      minio:
        condition: service_healthy
    env_file:
      - .env
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      mc mb myminio/raw || true;
      mc mb myminio/raw/processed/ || true;
      exit 0;
      "

  airflow-webserver:
    <<: *airflow-common
    restart: always
    depends_on:
      postgres:
          condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
      - "8081:8081"
    command: >
      bash -c "
      exec airflow webserver
      "
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 20s
      timeout: 10s
      retries: 5

  airflow-scheduler:
    <<: *airflow-common
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    command: >
      bash -c "
      exec airflow scheduler
      "
    healthcheck:
      test: ["CMD", "airflow", "jobs", "check", "--job-type", "SchedulerJob"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
  minio_data: